version: '3'

services:
  jihua-blazor:
    build: 
      context: ./WebServer
    image: mqttrobot_webserver
    container_name: mqttrobot_webserver
    volumes:
      - ./Data:/app/Data
      - ./Configs/WebServer/Properties:/app/Properties
    network_mode: host
  jihua-mqttdb:
    build: 
      context: ./MapServer
      network: host
    image: mqttrobot_mapserver
    container_name: mqttrobot_mapserver
    volumes:
      - ./Data:/app/Data
      - ./Configs/MapServer/Configs/:/app/Configs
    network_mode: host